FROM node as builder

WORKDIR /usr/src/app
RUN git clone https://github.com/ASolobaev/java-reboot-client.git &&\
 cd java-reboot-client &&\
 npm ci &&\
 npm run build

FROM nginx

COPY -- from builder /usr/src/app/java-reboot-client/nginx/nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /usr/src/app/java-reboot-client/build /usr/share/nginx/html

EXPOSE 3000 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
